on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '26'
      - run: npm install
      - run: npm run typecheck
      - run: npm run lint -- --deny-warnings
      - run: npm test -- --coverage
